# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmigrate < Formula
  desc "A Terraform state migration tool for GitOps"
  homepage "https://github.com/minamijoyo/tfmigrate"
  version "0.3.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.3.12/tfmigrate_0.3.12_darwin_arm64.tar.gz"
      sha256 "ab3c6c460965a93bdb556ee0b162131e51806197637ffb0f847aa747ab38d32a"

      def install
        bin.install "tfmigrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.3.12/tfmigrate_0.3.12_darwin_amd64.tar.gz"
      sha256 "7a43732eb080314452a3cc1f312dfb76ec7ed155d6a2af19f19acee8ab668fdf"

      def install
        bin.install "tfmigrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.3.12/tfmigrate_0.3.12_linux_arm64.tar.gz"
      sha256 "35659bf012632f55814b871cc5e9b7449d97c400c073234f6b269450c8357668"

      def install
        bin.install "tfmigrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.3.12/tfmigrate_0.3.12_linux_amd64.tar.gz"
      sha256 "71cee4bf4381225e057625cf0da9c142169cc1fb13c678abfe00bf50e71458f3"

      def install
        bin.install "tfmigrate"
      end
    end
  end

  test do
    system "#{bin}/tfmigrate -v"
  end
end
