# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmigrate < Formula
  desc "A Terraform state migration tool for GitOps"
  homepage "https://github.com/minamijoyo/tfmigrate"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.2.2/tfmigrate_0.2.2_darwin_amd64.tar.gz"
    sha256 "8fb6a068296cfcd5569833dcfc1ee51689d74e25043c6474f093f8bd39cb4772"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.2.2/tfmigrate_0.2.2_linux_amd64.tar.gz"
    sha256 "46d0ec7bf6d909a5e91c033381a54eb6966b277b8a03a08e3d60c512100ca3e3"
  end

  def install
    bin.install "tfmigrate"
  end

  test do
    system "#{bin}/tfmigrate -v"
  end
end
