# This file was generated by GoReleaser. DO NOT EDIT.
class Tfmigrate < Formula
  desc "A Terraform state migration tool for GitOps"
  homepage "https://github.com/minamijoyo/tfmigrate"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.2.1/tfmigrate_0.2.1_darwin_amd64.tar.gz"
    sha256 "11cabc80285597a0c6aafb1e0876e101ef96d958a2d92d90511780345155b937"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/minamijoyo/tfmigrate/releases/download/v0.2.1/tfmigrate_0.2.1_linux_amd64.tar.gz"
    sha256 "6ffcf48d0f5f2fbfbc686d5adbbe40621acaa9664342e855f4c4b4601d2a8564"
  end

  def install
    bin.install "tfmigrate"
  end

  test do
    system "#{bin}/tfmigrate -v"
  end
end
